apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pikatwo-be-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "pikatwo.kbfg.kubepia.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pikatwo-be-svc
            port:
              number: 5000
